/***********************************
 * Copyright (c) 2024 Roger Brown.
 * Licensed under the MIT License.
 ****/

import "oaidl.idl"; 

[
	object,
	uuid(58fb54de-ae65-4676-8171-4ec1eceb1d9d),
	oleautomation,
	dual,
	helpstring("interface IHelloWorld")
]
interface IHelloWorld : IDispatch
{
	HRESULT GetMessage(int Hint,[retval,out] BSTR *lpMessage);
}

[
	uuid(0bf2e8d0-41c4-4546-9ef8-85073106ae80)
]
library RhubarbGeekNzDispLib
{
	importlib("stdole32.tlb");
	interface IHelloWorld;
}
